CREATE DATABASE STAART;

USE STAART;

CREATE SCHEMA STREAM;

CREATE TABLE MANTIMENTO(
	nome VARCHAR(200),
    data_de_vencimento DATE
);

CREATE TABLE stream.ELETRONICOS(
	nome VARCHAR(200),
    DESCRICAO VARCHAR(200)
);
















CREATE TABLE STREAM.USERS(
	ID_USER INT PRIMARY KEY,
    NAME VARCHAR(255),
    USERNAME VARCHAR(255),
    PASSWORD VARCHAR(100),
    CREATED_AT DATETIME
);



CREATE TABLE STREAM.CATEGORIES(
	ID_CATEGORY INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) UNIQUE NOT NULL
);



INSERT INTO STREAM.CATEGORIES(NAME) VALUES('DESENHO');

SELECT * FROM STREAM.CATEGORIES;
SELECT ID_CATEGORY FROM STREAM.CATEGORIES;
SELECT ID_CATEGORY FROM STREAM.CATEGORIES WHERE ID_CATEGORY > 1;



INSERT INTO STREAM.USERS
(ID_USER, NAME, USERNAME, PASSWORD, CREATED_AT)
VALUES(4, 'THAISSA', 'THAI', '1234', CURRENT_DATE());

SELECT *
FROM STREAM.USERS;


UPDATE STREAM.USERS 
SET PASSWORD = '1234', USERNAME = 'DANILEAO' 
WHERE ID_USER = 1;

SELECT * FROM STREAM.CATEGORIES;

DELETE
FROM STREAM.CATEGORIES
WHERE ID_CATEGORY = 4
;



ALTER TABLE STREAM.USERS
ADD CONSTRAINT NAMME_UNIQUE UNIQUE(USERNAME);


























INSERT INTO STREAM.CATEGORIES(NAME) VALUES('DRAMA');



SELECT * FROM STREAM.CATEGORIES;

-- IN
SELECT * FROM STREAM.CATEGORIES
WHERE ID_CATEGORY IN(1,3,6);

-- BETWEEN
SELECT * FROM STREAM.CATEGORIES
WHERE ID_CATEGORY BETWEEN 3 AND 6;

-- != <>
SELECT * FROM STREAM.CATEGORIES 
WHERE NAME != 'COMEDIA';
-- =
SELECT * FROM STREAM.CATEGORIES 
WHERE ID_CATEGORY = 6;

INSERT INTO STREAM.USERS 
(ID_USER, NAME, USERNAME, PASSWORD, CREATED_AT)
VALUES(6, 'DANIEL', 'DANIEL', NULL, CURRENT_DATE());

-- IS NULL / IS NOT NULL
SELECT * FROM STREAM.USERS
WHERE PASSWORD IS NULL;

SELECT * FROM STREAM.USERS
WHERE PASSWORD IS NOT NULL;

-- LIKE
SELECT * FROM STREAM.USERS
WHERE NAME LIKE '%A%'; -- DANI% = DANI... | %ELE = ...ELE


-- >  < | >= <=
SELECT * FROM STREAM.USERS 
WHERE ID_USER >= 2;




CREATE TABLE STREAM.PROFILE(
	ID_PROFILE INT AUTO_INCREMENT PRIMARY KEY,
    ID_USER_PROFILE INT,
    BIO VARCHAR(300) DEFAULT 'MINHA BIO',
    AVATAR_URL VARCHAR(200),
    FOREIGN KEY(ID_USER_PROFILE) REFERENCES STREAM.USERS(ID_USER)
);

SELECT * FROM STREAM.USERS;

INSERT INTO STREAM.PROFILE(ID_USER_PROFILE, AVATAR_URL) 
VALUES(2, 'http://google.com.br/avatar_dani');

SELECT * FROM STREAM.PROFILE;


delete from stream.profile where id_profile > 1;

ALTER TABLE STREAM.PROFILE DROP FOREIGN KEY profile_ibfk_1;

ALTER TABLE STREAM.PROFILE
ADD CONSTRAINT FOREIGN KEY(ID_USER_PROFILE) REFERENCES STREAM.USERS(ID_USER),
ADD CONSTRAINT UNIQUE(ID_USER_PROFILE);



CREATE TABLE STREAM.CONTENT(
	ID_CONTENT INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(300),
    ID_CATEGORY INT,
    DURATION TIME,
    FOREIGN KEY(ID_CATEGORY) REFERENCES STREAM.CATEGORIES (ID_CATEGORY)
);

SELECT * FROM STREAM.CATEGORIES;

INSERT INTO STREAM.CONTENT(NAME, ID_CATEGORY, DURATION)
VALUES('GALINHA PINTADINHA', 5, '02:00');

SELECT * FROM STREAM.CONTENT;


CREATE TABLE STREAM.USERS_CONTENTS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_USER INT,
    ID_CONTENT INT,
    TIME_STOPPED TIME,
    NOTE INT,
    FOREIGN KEY(ID_USER) REFERENCES STREAM.USERS(ID_USER),
    FOREIGN KEY(ID_CONTENT) REFERENCES STREAM.CONTENT(ID_CONTENT)
);

SELECT * FROM STREAM.USERS;
SELECT * FROM STREAM.CONTENT;
INSERT INTO STREAM.USERS_CONTENTS(ID_USER, ID_CONTENT, TIME_STOPPED, NOTE)
VALUES(6,1,'00:50',10);
INSERT INTO STREAM.USERS_CONTENTS(ID_USER, ID_CONTENT, TIME_STOPPED, NOTE)
VALUES(6,2,'00:34',8);

INSERT INTO STREAM.USERS_CONTENTS(ID_USER, ID_CONTENT, TIME_STOPPED, NOTE)
VALUES(1,1,'01:20',10);

SELECT * FROM STREAM.USERS_CONTENTS;







SELECT * FROM STREAM.USERS_CONTENTS
INNER JOIN STREAM.USERS
ON STREAM.USERS_CONTENTS.ID_USER = STREAM.USERS.ID_USER;

SELECT * FROM STREAM.USERS
LEFT JOIN STREAM.USERS_CONTENTS
ON STREAM.USERS.ID_USER = STREAM.USERS_CONTENTS.ID_USER;

SELECT * FROM STREAM.USERS
LEFT JOIN STREAM.USERS_CONTENTS
ON STREAM.USERS.ID_USER = STREAM.USERS_CONTENTS.ID_USER
WHERE STREAM.USERS_CONTENTS.ID_USER IS NULL;


SELECT * FROM STREAM.CONTENT;
SELECT * FROM STREAM.USERS_CONTENTS
RIGHT JOIN STREAM.CONTENT
ON STREAM.USERS_CONTENTS.ID_CONTENT = STREAM.CONTENT.ID_CONTENT;


SELECT * FROM STREAM.CONTENT;
SELECT * FROM STREAM.USERS_CONTENTS
RIGHT JOIN STREAM.CONTENT
ON STREAM.USERS_CONTENTS.ID_CONTENT = STREAM.CONTENT.ID_CONTENT
WHERE STREAM.USERS_CONTENTS.ID_CONTENT IS NULL;

SELECT * FROM STREAM.USERS_CONTENTS
RIGHT JOIN STREAM.CONTENT
ON STREAM.USERS_CONTENTS.ID_CONTENT = STREAM.CONTENT.ID_CONTENT
UNION
SELECT * FROM STREAM.USERS_CONTENTS
LEFT JOIN STREAM.CONTENT
ON STREAM.USERS_CONTENTS.ID_CONTENT = STREAM.CONTENT.ID_CONTENT;



SELECT * FROM STREAM.USERS_CONTENTS
RIGHT JOIN STREAM.CONTENT
ON STREAM.USERS_CONTENTS.ID_CONTENT = STREAM.CONTENT.ID_CONTENT
WHERE STREAM.USERS_CONTENTS.ID_CONTENT IS NULL OR STREAM.CONTENT.ID_CONTENT IS NULL
UNION
SELECT * FROM STREAM.USERS_CONTENTS
LEFT JOIN STREAM.CONTENT
ON STREAM.USERS_CONTENTS.ID_CONTENT = STREAM.CONTENT.ID_CONTENT
WHERE STREAM.USERS_CONTENTS.ID_CONTENT IS NULL OR STREAM.CONTENT.ID_CONTENT IS NULL;


INSERT INTO STREAM.USERS_CONTENTS(ID_USER, ID_CONTENT, TIME_STOPPED, NOTE)
VALUES(6,3,'01:40',7);

SELECT COUNT(*) FROM STREAM.USERS_CONTENTS;

-- COUNT
SELECT COUNT(*) FROM STREAM.CONTENT;

-- MAX
SELECT MAX(NOTE)
FROM STREAM.USERS_CONTENTS
WHERE ID_CONTENT = 3;

-- MIN
SELECT MIN(NOTE)
FROM STREAM.USERS_CONTENTS
WHERE ID_CONTENT = 3;

-- AVG
SELECT AVG(NOTE)
FROM STREAM.USERS_CONTENTS
WHERE ID_CONTENT = 3;

-- SUM
SELECT SUM(NOTE)
FROM STREAM.USERS_CONTENTS
WHERE ID_CONTENT = 3;

SELECT * FROM STREAM.USERS_CONTENTS WHERE ID_CONTENT = 3;



SELECT * FROM STREAM.CONTENT
ORDER BY ID_CONTENT DESC; -- DESC(DECRESCENTE) / ASC(CRESCENTE)

SELECT * FROM STREAM.CONTENT
ORDER BY DURATION ASC;





SELECT UC.TIME_STOPPED, U.NAME, C.DURATION, C.NAME 
FROM STREAM.USERS_CONTENTS UC
INNER JOIN STREAM.USERS U
ON UC.ID_USER = U.ID_USER
INNER JOIN STREAM.CONTENT C
ON UC.ID_CONTENT = C.ID_CONTENT
WHERE UC.TIME_STOPPED < C.DURATION;

UPDATE STREAM.USERS_CONTENTS
SET TIME_STOPPED = '02:00' 
WHERE ID = 3;



SELECT * FROM STREAM.USERS_CONTENTS
INNER JOIN STREAM.USERS
ON STREAM.USERS_CONTENTS.ID_USER = STREAM.USERS.ID_USER
INNER JOIN STREAM.CONTENT
ON STREAM.USERS_CONTENTS.ID_CONTENT = STREAM.CONTENT.ID_CONTENT
WHERE STREAM.USERS_CONTENTS.TIME_STOPPED >= STREAM.CONTENT.DURATION;
 






SELECT U.ID_USER, COUNT(UC.ID) FROM STREAM.USERS_CONTENTS UC
INNER JOIN STREAM.USERS U
ON UC.ID_USER = U.ID_USER
INNER JOIN STREAM.CONTENT C
ON UC.ID_CONTENT = C.ID_CONTENT
WHERE UC.TIME_STOPPED < C.DURATION
GROUP BY U.ID_USER;



